import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.why': 'Why Sarmoyavest',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.advantages': 'Advantages',
    'nav.insights': 'Insights',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.uploadProject': 'Upload Project',
    
    // Home Page
    'home.hero.badge': 'Connecting Innovators Globally',
    'home.hero.title': 'Connecting Visionaries and',
    'home.hero.titleHighlight': 'Investors',
    'home.hero.description': 'Sarmoyavest connects young innovators and early-stage startups with global investors and mentors. Making innovation funding accessible, transparent, and borderless.',
    'home.hero.browseProjects': 'Browse Projects',
    'home.hero.submitStartup': 'Submit Your Startup',
    'home.mission.title': 'Our Mission',
    'home.mission.description': 'We\'re building bridges between talented entrepreneurs in emerging markets and the global investment community. Our platform provides visibility, support, and opportunities for startups that might otherwise go unnoticed.',
    'home.mission.learnMore': 'Learn More About Us',
    'home.features.title': 'Why Choose Sarmoyavest',
    'home.features.subtitle': 'Built specifically for early-stage startups from developing regions',
    'home.features.globalReach': 'Global Reach',
    'home.features.globalReachDesc': 'Connect with investors and mentors from around the world',
    'home.features.community': 'Community First',
    'home.features.communityDesc': 'Join a thriving community of innovators and entrepreneurs',
    'home.features.earlyStage': 'Early-Stage Focus',
    'home.features.earlyStageDesc': 'Support for startups at every stage of their journey',
    'home.features.transparent': 'Transparent Process',
    'home.features.transparentDesc': 'Clear, secure, and straightforward funding process',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.description': 'Whether you\'re an innovator looking for funding or an investor seeking the next big opportunity, Sarmoyavest is your platform.',
    'home.cta.joinInnovator': 'Join as Innovator',
    'home.cta.exploreInvestor': 'Explore as Investor',
    
    // Auth
    'auth.title': 'Welcome to Sarmoyavest',
    'auth.subtitle': 'Join our community of innovators and investors',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.role': 'I am an',
    'auth.innovator': 'Innovator',
    'auth.investor': 'Investor',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Create Account',
    'auth.success': 'Success!',
    'auth.error': 'Error',
    
    // Projects
    'projects.title': 'Explore Projects',
    'projects.subtitle': 'Discover innovative startups seeking funding',
    'projects.search': 'Search projects...',
    'projects.filterCategory': 'All Categories',
    'projects.filterRegion': 'All Regions',
    'projects.sortNewest': 'Newest',
    'projects.sortViews': 'Most Viewed',
    'projects.noProjects': 'No projects found',
    'projects.views': 'views',
    
    // Upload Project
    'upload.title': 'Submit Your Project',
    'upload.subtitle': 'Share your innovative idea with potential investors',
    'upload.projectTitle': 'Project Title',
    'upload.description': 'Description',
    'upload.category': 'Category',
    'upload.region': 'Region',
    'upload.fundingRange': 'Funding Range',
    'upload.telegram': 'Telegram Username',
    'upload.email': 'Email',
    'upload.images': 'Project Images',
    'upload.submit': 'Submit Project',
    'upload.success': 'Project submitted successfully!',
    'upload.error': 'Failed to submit project',
    
    // Advantages
    'advantages.title': 'Advantages of Sarmoyavest',
    'advantages.subtitle': 'Why choose our platform to connect innovators and investors',
    'advantages.global.title': 'Global Reach',
    'advantages.global.desc': 'We unite young entrepreneurs and investors from all over the world, starting with Uzbekistan and Central Asia.',
    'advantages.security.title': 'Security and Transparency',
    'advantages.security.desc': 'We ensure the security and transparency of all operations on the platform, protecting participants\' interests.',
    'advantages.support.title': 'Support for Early-Stage Startups',
    'advantages.support.desc': 'We help early innovators showcase and grow their ideas with confidence.',
    'advantages.bilingual.title': 'Bilingual Interface',
    'advantages.bilingual.desc': 'Full support for English and Russian languages to serve our diverse community.',
    
    // About Page
    'about.title': 'About Sarmoyavest',
    'about.subtitle': 'Empowering early-stage founders from developing regions to connect with global opportunities',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Sarmoyavest was born from a simple observation: brilliant innovators in Central Asia and other developing regions face significant barriers in accessing global capital and mentorship.',
    'about.story.p2': 'While the world has become increasingly connected, the innovation funding ecosystem remains concentrated in traditional hubs. We believe this represents a massive missed opportunity for both investors and entrepreneurs.',
    'about.story.p3': 'Our platform breaks down these barriers by providing a transparent, accessible space where talent meets opportunity, regardless of geographic boundaries.',
    'about.values.title': 'Our Values',
    'about.values.accessibility': 'Accessibility',
    'about.values.accessibilityDesc': 'Making innovation funding accessible to founders everywhere, regardless of their location or network.',
    'about.values.transparency': 'Transparency',
    'about.values.transparencyDesc': 'Building trust through clear processes, honest communication, and secure interactions.',
    'about.values.innovation': 'Innovation',
    'about.values.innovationDesc': 'Championing bold ideas and supporting entrepreneurs who dare to think differently.',
    'about.vision.title': 'Our Vision',
    'about.vision.p1': 'We envision a world where innovation funding is truly borderless, where the quality of an idea matters more than the founder\'s postal code.',
    'about.vision.p2': 'Through Sarmoyavest, we\'re creating an ecosystem where:',
    'about.vision.li1': 'Talented founders from any region can showcase their innovations',
    'about.vision.li2': 'Investors discover untapped opportunities in emerging markets',
    'about.vision.li3': 'Mentors share their expertise with the next generation of entrepreneurs',
    'about.vision.li4': 'Communities collaborate across borders to solve global challenges',
    'about.vision.p3': 'We\'re not just building a platform – we\'re building a movement that recognizes and unleashes the potential of innovators everywhere.',
    'about.team.title': 'Meet the Team',
    'about.team.subtitle': 'A passionate team of young innovators and mentors empowering the next generation of entrepreneurs.',
    'about.team.vasliddin': 'Vasliddin Isomiddinov',
    'about.team.vasliddinRole': 'Founder & Director',
    'about.team.vasliddinDesc': 'Leads the vision, design, and development of Sarmoyavest. Oversees product direction and team coordination. Passionate about innovation and building a bridge between young entrepreneurs and investors.',
    'about.team.asadbek': 'Asadbek Ismoilov',
    'about.team.asadbekRole': 'Project Advisor',
    'about.team.asadbekDesc': 'Economics student at HKUST guiding Sarmoyavest\'s strategic and financial direction. Provides mentorship on scaling strategies and economic frameworks.',
    'about.team.adiba': 'Adiba Isabekova',
    'about.team.adibaRole': 'Head of Communications',
    'about.team.adibaDesc': 'Leads brand communication, storytelling, and media presence. Ensures Sarmoyavest\'s message connects clearly and creatively with the public.',
    'about.team.dauren': 'Dauren Ibragim',
    'about.team.daurenRole': 'Operations & Partnerships Lead',
    'about.team.daurenDesc': 'Coordinates cross-border partnerships and manages project operations. Focused on building collaborations and ensuring smooth execution.',
    
    // Footer
    'footer.tagline': 'Connecting innovators with investors, empowering the next generation of global startups.',
    'footer.platform': 'Platform',
    'footer.aboutUs': 'About Us',
    'footer.services': 'Services',
    'footer.browseProjects': 'Browse Projects',
    'footer.resources': 'Resources',
    'footer.resourcesLink': 'Resources',
    'footer.contact': 'Contact',
    'footer.connect': 'Connect',
    'footer.copyright': '© {year} Sarmoyavest. All rights reserved.',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.formTitle': 'Send us a message',
    'contact.name': 'Name',
    'contact.emailLabel': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.namePlaceholder': 'Your full name',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.subjectPlaceholder': 'What\'s this about?',
    'contact.messagePlaceholder': 'Tell us more...',
    'contact.send': 'Send Message',
    'contact.infoTitle': 'Contact Information',
    'contact.email': 'Email',
    'contact.location': 'Location',
    'contact.locationText': 'Jizzakh, Uzbekistan',
    'contact.followUs': 'Follow Us',
    'contact.officeHours': 'Contact Hours',
    'contact.hoursText': 'We\u2019re available online and typically respond within 24 hours.\nMonday \u2013 Saturday: Active\nSunday: Limited response',
    'contact.faqTitle': 'Frequently Asked Questions',
    'contact.faq1Q': 'How do I submit my startup?',
    'contact.faq1A': 'Simply sign up for an account, complete your profile, and submit your project details. Your startup will be reviewed and published on our platform.',
    'contact.faq2Q': 'Is Sarmoyavest free to use?',
    'contact.faq2A': 'Yes! Our platform is completely free for both innovators and investors. We believe in making innovation funding accessible to everyone.',
    'contact.faq3Q': 'What types of startups can join?',
    'contact.faq3A': 'We focus on early-stage startups (pre-seed and seed) from developing regions, particularly Central Asia. All industries and sectors are welcome.',
    'contact.missingInfo': 'Missing Information',
    'contact.fillFields': 'Please fill in all required fields.',
    'contact.messageSent': 'Message Sent!',
    'contact.willRespond': 'We\'ll get back to you as soon as possible.',
    
    // Projects Page
    'projects.heroTitle': 'Discover Startups',
    'projects.heroSubtitle': 'Browse innovative projects from talented founders across emerging markets',
    'projects.searchPlaceholder': 'Search by project name, country, or keyword...',
    'projects.showing': 'Showing {count} projects',
    'projects.founder': 'Founder:',
    'projects.contactFounder': 'Contact Founder',
    'projects.comingSoonTitle': 'More Projects Coming Soon',
    'projects.comingSoonText': 'This is just a preview. Once you sign up and submit your project, it will appear here for investors to discover.',
    'projects.submitStartup': 'Submit Your Startup',
    
    // Resources Page
    'resources.title': 'Resources',
    'resources.subtitle': 'Learn. Build. Grow — empowering innovators to create impact.',
    'resources.buildTitle': 'Build Your Idea',
    'resources.buildSubtitle': 'Clear, friendly guides to help you prepare and structure your startup submission.',
    'resources.guide1Title': 'How to Write a Clear Problem Statement',
    'resources.guide1Desc': 'Learn to articulate the problem your startup solves in a way that resonates with investors and users.',
    'resources.guide2Title': 'How to Describe Your Solution Effectively',
    'resources.guide2Desc': 'Master the art of presenting your solution clearly, highlighting what makes it unique and valuable.',
    'resources.guide3Title': 'Tips to Make Your Idea Stand Out',
    'resources.guide3Desc': 'Discover strategies to differentiate your startup and capture attention in a competitive landscape.',
    'resources.guide4Title': 'Understanding Your Target Audience',
    'resources.guide4Desc': 'Identify and analyze your ideal customers to build a product that truly meets their needs.',
    'resources.mentorshipTitle': 'Mentorship Program',
    'resources.mentorshipDesc': 'We\'re building a mentorship network to help innovators refine their ideas with expert guidance. Connect with mentors from top universities who understand your journey and can provide valuable insights to take your startup to the next level.',
    'resources.comingSoon': 'Coming Soon',
    'resources.oneOnOne': 'One-on-one sessions',
    'resources.expertFeedback': 'Expert feedback',
    'resources.growthStrategies': 'Growth strategies',
    // Events
    'nav.events': 'Events',
    'events.badge': 'Events & Milestones',
    'events.heroTitle': 'Events',
    'events.heroSubtitle': 'Join our upcoming sessions and explore the milestones that shaped our initiative.',
    'events.upcoming.heading': 'Upcoming Event',
    'events.upcoming.badge': 'Coming Soon',
    'events.upcoming.title': 'The Economics of Trust',
    'events.upcoming.date': 'May 15',
    'events.upcoming.desc': 'Featuring speakers from University of Birmingham and Nazarbayev University, the discussion will provide real-world insights into how talent is evaluated — and why markets don\u2019t always reward the best.',
    'events.upcoming.cta': 'Stay Tuned',
    'events.upcoming.soon': 'Coming soon',
    'events.past.heading': 'Our Journey So Far',
    'events.past.eventCount': 'event completed',
    'events.past.completedBadge': 'Completed',
    'events.past.firstEvent.date': 'January 16',
    'events.past.speakerSubtitle': 'Invited to share insights and inspire',
    'events.firstEvent.title': 'Inaugural Session: Foundations of Investing & Financial Thinking',
    'events.firstEvent.subtitle': 'Launching our initiative with our first guest speaker session',
    'events.whatHappened.title': 'Event Overview',
    'events.whatHappened.desc': 'The inaugural session marked the official launch of our initiative, bringing together a focused group of students interested in investing. The session was interactive, allowing attendees to engage in discussion and ask questions.',
    'events.guestSpeaker.title': 'Guest Speaker',
    'events.guestSpeaker.name': 'Asadbek Ismoilov',
    'events.guestSpeaker.role': 'Project Advisor',
    'events.guestSpeaker.bio': 'Asadbek Ismoilov, also known as Levsha, joined the event as our project advisor and guest speaker. As an economics student at HKUST, he shared valuable insights into financial literacy, investment thinking, and the mindset required to succeed in modern financial environments.',
    'events.gallery.title': 'Event Gallery',
    'events.gallery.photo1': 'Upload featured event photo',
    'events.gallery.photo2': 'Upload event photo 2',
    'events.gallery.photo3': 'Upload event photo 3',
    'events.gallery.featured': 'Featured',
    'events.whyItMattered.title': 'Why It Mattered',
    'events.whyItMattered.desc': '[Explain why this first event was important for your organization and community — the impact it had, what it meant for your initiative, and how it set the stage for future events.]',
    'events.keyInsights.title': 'Key Insights & Takeaways',
    'events.keyInsights.p1': 'It demonstrated that even a small, committed group can create meaningful discussions and begin shaping a culture of informed financial decision-making.',
    'events.keyInsights.p2': 'The success of this inaugural session sets the stage for future events, including larger lectures, guest speaker sessions, and expanded participation.',
    'events.nav.previous': 'Previous Event',
    'events.nav.next': 'Next Event',
    'events.nav.counter': 'Event {current} of {total}',
    'events.secondEvent.date': 'March 10',
    'events.secondEvent.title': 'From Idea to Impact: Solving Urban Traffic in Tashkent',
    'events.secondEvent.subtitle': 'An interactive "From Paper to Practice" session',
    'events.secondEvent.overviewTitle': 'Event Overview',
    'events.secondEvent.overviewDesc': 'This session was designed as an interactive "From Paper to Practice" experience, where participants explored how economic thinking can be applied to real-world challenges. Using traffic congestion in Tashkent as a case study, the session focused on evaluating practical solutions not only from a theoretical perspective, but also through the lens of feasibility, investment potential, and real-life implementation.',
    'events.secondEvent.galleryTitle': 'Event Gallery',
    'events.secondEvent.featured': 'Featured',
    'events.secondEvent.whatHappenedTitle': 'What Happened',
    'events.secondEvent.whatHappenedDesc': 'Attendees were divided into groups, with each group assigned to analyze and defend one solution. After structured discussions, each group presented their arguments, focusing on effectiveness, cost, scalability, and potential challenges. The session concluded with an open debate, where participants evaluated which solution would be most viable in the context of Tashkent.',
    'events.secondEvent.impactTitle': 'Impact',
    'events.secondEvent.impactDesc': 'This session marked a shift toward more interactive and application-based learning within Sarmoyavest. By combining economic theory with real-world problem-solving, participants were able to think critically, engage in meaningful discussions, and approach challenges from both entrepreneurial and analytical perspectives.',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.why': 'Почему Sarmoyavest',
    'nav.projects': 'Проекты',
    'nav.contact': 'Контакты',
    'nav.advantages': 'Преимущества',
    'nav.insights': 'Инсайты',
    'nav.events': 'Мероприятия',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.logout': 'Выйти',
    'nav.uploadProject': 'Загрузить проект',
    
    // Home Page
    'home.hero.badge': 'Соединяем новаторов по всему миру',
    'home.hero.title': 'Соединяем визионеров и',
    'home.hero.titleHighlight': 'Инвесторов',
    'home.hero.description': 'Sarmoyavest соединяет молодых новаторов и стартапы на ранней стадии с глобальными инвесторами и менторами. Делаем финансирование инноваций доступным, прозрачным и безграничным.',
    'home.hero.browseProjects': 'Просмотреть проекты',
    'home.hero.submitStartup': 'Подать заявку',
    'home.mission.title': 'Наша миссия',
    'home.mission.description': 'Мы строим мосты между талантливыми предпринимателями на развивающихся рынках и мировым инвестиционным сообществом. Наша платформа обеспечивает видимость, поддержку и возможности для стартапов, которые иначе могли бы остаться незамеченными.',
    'home.mission.learnMore': 'Узнать больше о нас',
    'home.features.title': 'Почему выбирают Sarmoyavest',
    'home.features.subtitle': 'Создано специально для стартапов на ранней стадии из развивающихся регионов',
    'home.features.globalReach': 'Глобальный охват',
    'home.features.globalReachDesc': 'Связь с инвесторами и менторами со всего мира',
    'home.features.community': 'Сообщество на первом месте',
    'home.features.communityDesc': 'Присоединяйтесь к процветающему сообществу новаторов и предпринимателей',
    'home.features.earlyStage': 'Фокус на ранних стадиях',
    'home.features.earlyStageDesc': 'Поддержка стартапов на каждом этапе их пути',
    'home.features.transparent': 'Прозрачный процесс',
    'home.features.transparentDesc': 'Четкий, безопасный и понятный процесс финансирования',
    'home.cta.title': 'Готовы начать?',
    'home.cta.description': 'Независимо от того, являетесь ли вы новатором, ищущим финансирование, или инвестором, ищущим следующую большую возможность, Sarmoyavest - ваша платформа.',
    'home.cta.joinInnovator': 'Присоединиться как новатор',
    'home.cta.exploreInvestor': 'Исследовать как инвестор',
    
    // Auth
    'auth.title': 'Добро пожаловать в Sarmoyavest',
    'auth.subtitle': 'Присоединяйтесь к нашему сообществу новаторов и инвесторов',
    'auth.login': 'Вход',
    'auth.signup': 'Регистрация',
    'auth.fullName': 'Полное имя',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.role': 'Я',
    'auth.innovator': 'Новатор',
    'auth.investor': 'Инвестор',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.loginButton': 'Войти',
    'auth.signupButton': 'Создать аккаунт',
    'auth.success': 'Успешно!',
    'auth.error': 'Ошибка',
    
    // Projects
    'projects.title': 'Обзор проектов',
    'projects.subtitle': 'Откройте для себя инновационные стартапы, ищущие финансирование',
    'projects.search': 'Поиск проектов...',
    'projects.filterCategory': 'Все категории',
    'projects.filterRegion': 'Все регионы',
    'projects.sortNewest': 'Новые',
    'projects.sortViews': 'Популярные',
    'projects.noProjects': 'Проекты не найдены',
    'projects.views': 'просмотров',
    
    // Upload Project
    'upload.title': 'Загрузить проект',
    'upload.subtitle': 'Поделитесь своей инновационной идеей с потенциальными инвесторами',
    'upload.projectTitle': 'Название проекта',
    'upload.description': 'Описание',
    'upload.category': 'Категория',
    'upload.region': 'Регион',
    'upload.fundingRange': 'Диапазон финансирования',
    'upload.telegram': 'Telegram',
    'upload.email': 'Email',
    'upload.images': 'Изображения проекта',
    'upload.submit': 'Отправить проект',
    'upload.success': 'Проект успешно отправлен!',
    'upload.error': 'Не удалось отправить проект',
    
    // Advantages
    'advantages.title': 'Преимущества Sarmoyavest',
    'advantages.subtitle': 'Почему стоит выбрать нашу платформу для соединения новаторов и инвесторов',
    'advantages.global.title': 'Глобальный охват',
    'advantages.global.desc': 'Мы объединяем молодых предпринимателей и инвесторов со всего мира, начиная с Узбекистана и Центральной Азии.',
    'advantages.security.title': 'Безопасность и прозрачность',
    'advantages.security.desc': 'Мы обеспечиваем безопасность и прозрачность всех операций на платформе, защищая интересы участников.',
    'advantages.support.title': 'Поддержка стартапов на ранней стадии',
    'advantages.support.desc': 'Мы помогаем начинающим новаторам демонстрировать и развивать свои идеи с уверенностью.',
    'advantages.bilingual.title': 'Двуязычный интерфейс',
    'advantages.bilingual.desc': 'Полная поддержка английского и русского языков для обслуживания нашего разнообразного сообщества.',
    
    // About Page
    'about.title': 'О Sarmoyavest',
    'about.subtitle': 'Расширяем возможности основателей на ранней стадии из развивающихся регионов для связи с глобальными возможностями',
    'about.story.title': 'Наша история',
    'about.story.p1': 'Sarmoyavest родился из простого наблюдения: гениальные новаторы в Центральной Азии и других развивающихся регионах сталкиваются со значительными барьерами в доступе к мировому капиталу и наставничеству.',
    'about.story.p2': 'Хотя мир стал более связанным, экосистема финансирования инноваций остается сосредоточенной в традиционных центрах. Мы считаем, что это представляет собой огромную упущенную возможность как для инвесторов, так и для предпринимателей.',
    'about.story.p3': 'Наша платформа разрушает эти барьеры, предоставляя прозрачное, доступное пространство, где талант встречается с возможностью, независимо от географических границ.',
    'about.values.title': 'Наши ценности',
    'about.values.accessibility': 'Доступность',
    'about.values.accessibilityDesc': 'Делаем финансирование инноваций доступным для основателей повсюду, независимо от их местоположения или связей.',
    'about.values.transparency': 'Прозрачность',
    'about.values.transparencyDesc': 'Строим доверие через четкие процессы, честное общение и безопасные взаимодействия.',
    'about.values.innovation': 'Инновации',
    'about.values.innovationDesc': 'Поддерживаем смелые идеи и предпринимателей, которые осмеливаются думать иначе.',
    'about.vision.title': 'Наше видение',
    'about.vision.p1': 'Мы видим мир, где финансирование инноваций действительно безгранично, где качество идеи важнее почтового индекса основателя.',
    'about.vision.p2': 'Через Sarmoyavest мы создаем экосистему, где:',
    'about.vision.li1': 'Талантливые основатели из любого региона могут демонстрировать свои инновации',
    'about.vision.li2': 'Инвесторы находят неиспользованные возможности на развивающихся рынках',
    'about.vision.li3': 'Менторы делятся своим опытом с следующим поколением предпринимателей',
    'about.vision.li4': 'Сообщества сотрудничают через границы для решения глобальных проблем',
    'about.vision.p3': 'Мы строим не просто платформу – мы строим движение, которое признает и раскрывает потенциал новаторов повсюду.',
    'about.team.title': 'Познакомьтесь с командой',
    'about.team.subtitle': 'Страстная команда молодых новаторов и менторов, расширяющих возможности следующего поколения предпринимателей.',
    'about.team.vasliddin': 'Васлиддин Исомиддинов',
    'about.team.vasliddinRole': 'Основатель и директор',
    'about.team.vasliddinDesc': 'Руководит видением, дизайном и разработкой Sarmoyavest. Курирует направление продукта и координацию команды. Увлечен инновациями и строительством моста между молодыми предпринимателями и инвесторами.',
    'about.team.asadbek': 'Асадбек Исмоилов',
    'about.team.asadbekRole': 'Советник проекта',
    'about.team.asadbekDesc': 'Студент экономики в HKUST, направляющий стратегическое и финансовое направление Sarmoyavest. Предоставляет наставничество по стратегиям масштабирования и экономическим основам.',
    'about.team.adiba': 'Адиба Исабекова',
    'about.team.adibaRole': 'Глава по коммуникациям',
    'about.team.adibaDesc': 'Руководит коммуникацией бренда, сторителлингом и присутствием в медиа. Обеспечивает, чтобы послание Sarmoyavest связывалось четко и творчески с общественностью.',
    'about.team.dauren': 'Даурен Ибрагим',
    'about.team.daurenRole': 'Руководитель операций и партнерств',
    'about.team.daurenDesc': 'Координирует трансграничные партнерства и управляет операциями проекта. Сосредоточен на построении сотрудничества и обеспечении плавного выполнения.',
    
    // Footer
    'footer.tagline': 'Соединяем новаторов с инвесторами, расширяя возможности следующего поколения глобальных стартапов.',
    'footer.platform': 'Платформа',
    'footer.aboutUs': 'О нас',
    'footer.services': 'Услуги',
    'footer.browseProjects': 'Просмотреть проекты',
    'footer.resources': 'Ресурсы',
    'footer.resourcesLink': 'Ресурсы',
    'footer.contact': 'Контакты',
    'footer.connect': 'Связаться',
    'footer.copyright': '© {year} Sarmoyavest. Все права защищены.',
    
    // Contact Page
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Есть вопросы? Мы будем рады услышать вас. Отправьте нам сообщение, и мы ответим как можно скорее.',
    'contact.formTitle': 'Отправить сообщение',
    'contact.name': 'Имя',
    'contact.emailLabel': 'Email',
    'contact.subject': 'Тема',
    'contact.message': 'Сообщение',
    'contact.namePlaceholder': 'Ваше полное имя',
    'contact.emailPlaceholder': 'ваш@email.com',
    'contact.subjectPlaceholder': 'О чем это?',
    'contact.messagePlaceholder': 'Расскажите подробнее...',
    'contact.send': 'Отправить сообщение',
    'contact.infoTitle': 'Контактная информация',
    'contact.email': 'Email',
    'contact.location': 'Местоположение',
    'contact.locationText': 'Джизак, Узбекистан',
    'contact.followUs': 'Подписывайтесь',
    'contact.officeHours': 'Часы связи',
    'contact.hoursText': 'Мы на связи онлайн и обычно отвечаем в течение 24 часов.\nПонедельник – Суббота: Активно\nВоскресенье: Ограниченный ответ',
    'contact.faqTitle': 'Часто задаваемые вопросы',
    'contact.faq1Q': 'Как мне подать заявку на стартап?',
    'contact.faq1A': 'Просто зарегистрируйтесь, заполните свой профиль и отправьте детали вашего проекта. Ваш стартап будет проверен и опубликован на нашей платформе.',
    'contact.faq2Q': 'Бесплатен ли Sarmoyavest?',
    'contact.faq2A': 'Да! Наша платформа полностью бесплатна как для новаторов, так и для инвесторов. Мы верим в то, что финансирование инноваций должно быть доступным для всех.',
    'contact.faq3Q': 'Какие типы стартапов могут присоединиться?',
    'contact.faq3A': 'Мы фокусируемся на стартапах на ранней стадии (пре-сид и сид) из развивающихся регионов, особенно Центральной Азии. Приветствуются все отрасли и секторы.',
    'contact.missingInfo': 'Недостающая информация',
    'contact.fillFields': 'Пожалуйста, заполните все обязательные поля.',
    'contact.messageSent': 'Сообщение отправлено!',
    'contact.willRespond': 'Мы свяжемся с вами как можно скорее.',
    
    // Projects Page
    'projects.heroTitle': 'Откройте стартапы',
    'projects.heroSubtitle': 'Просмотрите инновационные проекты от талантливых основателей с развивающихся рынков',
    'projects.searchPlaceholder': 'Поиск по названию проекта, стране или ключевому слову...',
    'projects.showing': 'Показано {count} проектов',
    'projects.founder': 'Основатель:',
    'projects.contactFounder': 'Связаться с основателем',
    'projects.comingSoonTitle': 'Скоро появятся новые проекты',
    'projects.comingSoonText': 'Это всего лишь предварительный просмотр. После регистрации и отправки вашего проекта, он появится здесь для инвесторов.',
    'projects.submitStartup': 'Подать заявку на стартап',
    
    // Resources Page
    'resources.title': 'Ресурсы',
    'resources.subtitle': 'Учитесь. Создавайте. Развивайтесь — расширяем возможности новаторов для создания влияния.',
    'resources.buildTitle': 'Создайте свою идею',
    'resources.buildSubtitle': 'Четкие, дружелюбные руководства, которые помогут вам подготовить и структурировать заявку на стартап.',
    'resources.guide1Title': 'Как написать четкое описание проблемы',
    'resources.guide1Desc': 'Научитесь формулировать проблему, которую решает ваш стартап, так, чтобы она находила отклик у инвесторов и пользователей.',
    'resources.guide2Title': 'Как эффективно описать ваше решение',
    'resources.guide2Desc': 'Овладейте искусством ясного представления вашего решения, подчеркивая то, что делает его уникальным и ценным.',
    'resources.guide3Title': 'Советы, как выделить вашу идею',
    'resources.guide3Desc': 'Откройте стратегии, чтобы дифференцировать ваш стартап и привлечь внимание в конкурентной среде.',
    'resources.guide4Title': 'Понимание вашей целевой аудитории',
    'resources.guide4Desc': 'Определите и проанализируйте ваших идеальных клиентов, чтобы создать продукт, который действительно отвечает их потребностям.',
    'resources.mentorshipTitle': 'Программа наставничества',
    'resources.mentorshipDesc': 'Мы создаем сеть наставничества, чтобы помочь новаторам усовершенствовать свои идеи с экспертным руководством. Свяжитесь с менторами из ведущих университетов, которые понимают ваш путь и могут предоставить ценные идеи, чтобы вывести ваш стартап на новый уровень.',
    'resources.comingSoon': 'Скоро',
    'resources.oneOnOne': 'Индивидуальные сессии',
    'resources.expertFeedback': 'Экспертная обратная связь',
    'resources.growthStrategies': 'Стратегии роста',

    // Events
    'events.badge': 'Мероприятия и вехи',
    'events.heroTitle': 'Мероприятия',
    'events.heroSubtitle': 'Присоединяйтесь к нашим предстоящим мероприятиям и узнайте о вехах, которые сформировали нашу инициативу.',
    'events.upcoming.heading': 'Предстоящее мероприятие',
    'events.upcoming.badge': 'Скоро',
    'events.upcoming.title': 'Экономика доверия',
    'events.upcoming.date': '15 мая',
    'events.upcoming.desc': 'С участием спикеров из Университета Бирмингема и Назарбаев Университета — обсуждение предоставит реальные взгляды на то, как оценивается талант и почему рынки не всегда вознаграждают лучших.',
    'events.upcoming.cta': 'Следите за обновлениями',
    'events.upcoming.soon': 'Скоро',
    'events.past.heading': 'Наш путь',
    'events.past.eventCount': 'мероприятие проведено',
    'events.past.completedBadge': 'Завершено',
    'events.past.firstEvent.date': '16 января',
    'events.past.speakerSubtitle': 'Приглашён поделиться опытом и вдохновить',
    'events.firstEvent.title': 'Первая сессия: Основы инвестирования и финансового мышления',
    'events.firstEvent.subtitle': 'Запуск нашей инициативы с первой сессией приглашенного спикера',
    'events.whatHappened.title': 'Обзор мероприятия',
    'events.whatHappened.desc': 'Первая сессия ознаменовала официальный запуск нашей инициативы, собрав целеустремленную группу студентов, интересующихся инвестированием. Сессия была интерактивной, позволяя участникам вести дискуссию и задавать вопросы.',
    'events.guestSpeaker.title': 'Приглашенный спикер',
    'events.guestSpeaker.name': 'Асадбек Исмоилов',
    'events.guestSpeaker.role': 'Советник проекта',
    'events.guestSpeaker.bio': 'Асадбек Исмоилов, также известный как Левша, присоединился к мероприятию в качестве советника проекта и приглашенного спикера. Будучи студентом экономического факультета HKUST, он поделился ценными знаниями о финансовой грамотности, инвестиционном мышлении и мировоззрении, необходимом для успеха в современных финансовых условиях.',
    'events.gallery.title': 'Галерея мероприятия',
    'events.gallery.photo1': 'Загрузить главное фото',
    'events.gallery.photo2': 'Загрузить фото 2',
    'events.gallery.photo3': 'Загрузить фото 3',
    'events.gallery.featured': 'Главное',
    'events.whyItMattered.title': 'Почему это важно',
    'events.whyItMattered.desc': '[Объясните, почему это первое мероприятие было важно для вашей организации и сообщества — какое влияние оно оказало и как подготовило почву для будущих мероприятий.]',
    'events.keyInsights.title': 'Ключевые выводы',
    'events.keyInsights.p1': 'Это показало, что даже небольшая, преданная группа может создавать содержательные дискуссии и формировать культуру осознанных финансовых решений.',
    'events.keyInsights.p2': 'Успех этой первой сессии создаёт основу для будущих мероприятий, включая более крупные лекции, выступления приглашённых спикеров и расширенное участие.',
    'events.nav.previous': 'Предыдущее мероприятие',
    'events.nav.next': 'Следующее мероприятие',
    'events.nav.counter': 'Мероприятие {current} из {total}',
    'events.secondEvent.date': '10 марта',
    'events.secondEvent.title': 'От идеи к результату: решение проблемы городского трафика в Ташкенте',
    'events.secondEvent.subtitle': 'Интерактивная сессия «От теории к практике»',
    'events.secondEvent.overviewTitle': 'Обзор мероприятия',
    'events.secondEvent.overviewDesc': 'Эта сессия была организована как интерактивный опыт «От теории к практике», где участники изучали, как экономическое мышление можно применять к реальным задачам. На примере транспортных пробок в Ташкенте сессия была сосредоточена на оценке практических решений не только с теоретической точки зрения, но и с точки зрения реализуемости, инвестиционного потенциала и реального внедрения.',
    'events.secondEvent.galleryTitle': 'Галерея мероприятия',
    'events.secondEvent.featured': 'Главное',
    'events.secondEvent.whatHappenedTitle': 'Что произошло',
    'events.secondEvent.whatHappenedDesc': 'Участники были разделены на группы, каждой из которых было поручено проанализировать и защитить одно решение. После структурированных обсуждений каждая группа представила свои аргументы, сосредоточившись на эффективности, стоимости, масштабируемости и потенциальных трудностях. Сессия завершилась открытыми дебатами, в ходе которых участники оценивали, какое решение было бы наиболее жизнеспособным в условиях Ташкента.',
    'events.secondEvent.impactTitle': 'Влияние',
    'events.secondEvent.impactDesc': 'Эта сессия стала шагом к более интерактивному и прикладному обучению в рамках Sarmoyavest. Сочетая экономическую теорию с решением реальных задач, участники смогли мыслить критически, вести содержательные обсуждения и подходить к вызовам как с предпринимательской, так и с аналитической точки зрения.',
  },
  uz: {
    // Navigation
    'nav.home': 'Bosh sahifa',
    'nav.about': 'Biz haqimizda',
    'nav.services': 'Xizmatlar',
    'nav.why': 'Nega Sarmoyavest',
    'nav.projects': 'Loyihalar',
    'nav.contact': 'Aloqa',
    'nav.advantages': 'Afzalliklar',
    'nav.insights': 'Tahlillar',
    'nav.events': 'Tadbirlar',
    'nav.login': 'Kirish',
    'nav.signup': 'Ro‘yxatdan o‘tish',
    'nav.logout': 'Chiqish',
    'nav.uploadProject': 'Loyiha yuklash',

    // Home Page
    'home.hero.badge': 'Innovatorlarni global miqyosda bog‘laymiz',
    'home.hero.title': 'Vizionerlar va',
    'home.hero.titleHighlight': 'Investorlar',
    'home.hero.description': 'Sarmoyavest yosh innovatorlar va boshlang‘ich bosqichdagi startaplarni global investorlar va mentorlar bilan bog‘laydi. Innovatsiyalarni moliyalashtirish ochiq, shaffof va chegarasiz bo‘lsin deb harakat qilamiz.',
    'home.hero.browseProjects': 'Loyihalarni ko‘rish',
    'home.hero.submitStartup': 'Startapingizni yuborish',
    'home.mission.title': 'Bizning maqsad',
    'home.mission.description': 'Biz rivojlanayotgan bozorlardagi iste’dodli tadbirkorlar va global investitsiya hamjamiyati o‘rtasida ko‘priklar quryapmiz. Platformamiz e’tiborga olinmasligi mumkin bo‘lgan startaplarga ko‘rinish, qo‘llab-quvvatlash va imkoniyatlar beradi.',
    'home.mission.learnMore': 'Biz haqimizda batafsil',
    'home.features.title': 'Nega Sarmoyavestni tanlaysiz',
    'home.features.subtitle': 'Rivojlanayotgan mintaqalardagi boshlang‘ich startaplar uchun maxsus yaratilgan',
    'home.features.globalReach': 'Global qamrov',
    'home.features.globalReachDesc': 'Dunyo bo‘ylab investorlar va mentorlar bilan bog‘laning',
    'home.features.community': 'Hamjamiyat birinchi o‘rinda',
    'home.features.communityDesc': 'Innovatorlar va tadbirkorlarning faol hamjamiyatiga qo‘shiling',
    'home.features.earlyStage': 'Boshlang‘ich bosqichga e’tibor',
    'home.features.earlyStageDesc': 'Startaplarni har bir bosqichda qo‘llab-quvvatlash',
    'home.features.transparent': 'Shaffof jarayon',
    'home.features.transparentDesc': 'Aniq, xavfsiz va tushunarli moliyalashtirish jarayoni',
    'home.cta.title': 'Boshlashga tayyormisiz?',
    'home.cta.description': 'Moliyalashtirish izlayotgan innovator yoki keyingi katta imkoniyatni izlayotgan investor bo‘lasizmi — Sarmoyavest siz uchun platforma.',
    'home.cta.joinInnovator': 'Innovator sifatida qo‘shilish',
    'home.cta.exploreInvestor': 'Investor sifatida ko‘rish',

    // Auth
    'auth.title': 'Sarmoyavestga xush kelibsiz',
    'auth.subtitle': 'Innovatorlar va investorlar hamjamiyatiga qo‘shiling',
    'auth.login': 'Kirish',
    'auth.signup': 'Ro‘yxatdan o‘tish',
    'auth.fullName': 'To‘liq ism',
    'auth.email': 'Email',
    'auth.password': 'Parol',
    'auth.role': 'Men',
    'auth.innovator': 'Innovator',
    'auth.investor': 'Investor',
    'auth.haveAccount': 'Hisobingiz bormi?',
    'auth.noAccount': 'Hisobingiz yo‘qmi?',
    'auth.loginButton': 'Kirish',
    'auth.signupButton': 'Hisob yaratish',
    'auth.success': 'Muvaffaqiyatli!',
    'auth.error': 'Xatolik',

    // Projects
    'projects.title': 'Loyihalarni o‘rganing',
    'projects.subtitle': 'Moliyalashtirish izlayotgan innovatsion startaplarni kashf eting',
    'projects.search': 'Loyihalarni qidirish...',
    'projects.filterCategory': 'Barcha toifalar',
    'projects.filterRegion': 'Barcha mintaqalar',
    'projects.sortNewest': 'Yangi',
    'projects.sortViews': 'Eng ko‘p ko‘rilgan',
    'projects.noProjects': 'Loyihalar topilmadi',
    'projects.views': 'ko‘rishlar',

    // Upload Project
    'upload.title': 'Loyihangizni yuboring',
    'upload.subtitle': 'Innovatsion g‘oyangizni potensial investorlar bilan baham ko‘ring',
    'upload.projectTitle': 'Loyiha nomi',
    'upload.description': 'Tavsif',
    'upload.category': 'Toifa',
    'upload.region': 'Mintaqa',
    'upload.fundingRange': 'Moliyalashtirish hajmi',
    'upload.telegram': 'Telegram',
    'upload.email': 'Email',
    'upload.images': 'Loyiha rasmlari',
    'upload.submit': 'Loyihani yuborish',
    'upload.success': 'Loyiha muvaffaqiyatli yuborildi!',
    'upload.error': 'Loyihani yuborib bo‘lmadi',

    // Advantages
    'advantages.title': 'Sarmoyavest afzalliklari',
    'advantages.subtitle': 'Nega innovatorlar va investorlarni bog‘lash uchun bizning platformamizni tanlash kerak',
    'advantages.global.title': 'Global qamrov',
    'advantages.global.desc': 'Biz O‘zbekiston va Markaziy Osiyodan boshlab, butun dunyodagi yosh tadbirkorlar va investorlarni birlashtiramiz.',
    'advantages.security.title': 'Xavfsizlik va shaffoflik',
    'advantages.security.desc': 'Platformadagi barcha amallarning xavfsizligi va shaffofligini ta’minlaymiz.',
    'advantages.support.title': 'Boshlang‘ich startaplarni qo‘llab-quvvatlash',
    'advantages.support.desc': 'Yosh innovatorlarga g‘oyalarini ishonch bilan ko‘rsatish va rivojlantirishda yordam beramiz.',
    'advantages.bilingual.title': 'Ko‘ptilli interfeys',
    'advantages.bilingual.desc': 'O‘zbek, ingliz va rus tillari uchun to‘liq qo‘llab-quvvatlash.',

    // About Page
    'about.title': 'Sarmoyavest haqida',
    'about.subtitle': 'Rivojlanayotgan mintaqalardagi boshlang‘ich asoschilarni global imkoniyatlarga ulaymiz',
    'about.story.title': 'Bizning hikoya',
    'about.story.p1': 'Sarmoyavest oddiy kuzatuvdan tug‘ildi: Markaziy Osiyo va boshqa rivojlanayotgan mintaqalardagi iste’dodli innovatorlar global kapital va mentorlikka kirishda jiddiy to‘siqlarga duch keladi.',
    'about.story.p2': 'Dunyo o‘zaro bog‘langan bo‘lsa-da, innovatsiyalarni moliyalashtirish ekotizimi an’anaviy markazlarda to‘plangan. Bu ham investorlar, ham tadbirkorlar uchun katta yo‘qotilgan imkoniyat.',
    'about.story.p3': 'Platformamiz bu to‘siqlarni buzadi va iste’dod imkoniyat bilan uchrashadigan shaffof va ochiq makon yaratadi.',
    'about.values.title': 'Bizning qadriyatlar',
    'about.values.accessibility': 'Ochiqlik',
    'about.values.accessibilityDesc': 'Innovatsiyalarni moliyalashtirishni har qanday joydagi asoschilar uchun ochiq qilamiz.',
    'about.values.transparency': 'Shaffoflik',
    'about.values.transparencyDesc': 'Aniq jarayonlar, halol muloqot va xavfsiz o‘zaro aloqalar orqali ishonch quramiz.',
    'about.values.innovation': 'Innovatsiya',
    'about.values.innovationDesc': 'Jasur g‘oyalarni qo‘llab-quvvatlaymiz va boshqacha fikrlovchi tadbirkorlarni qadrlaymiz.',
    'about.vision.title': 'Bizning maqsad-niyat',
    'about.vision.p1': 'Innovatsiyalarni moliyalashtirish chinakam chegarasiz bo‘lgan, g‘oya sifatining ahamiyati asoschining yashash joyidan muhimroq bo‘lgan dunyoni tasavvur qilamiz.',
    'about.vision.p2': 'Sarmoyavest orqali biz quyidagi ekotizimni yaratamiz:',
    'about.vision.li1': 'Har qanday mintaqadagi iste’dodli asoschilar innovatsiyalarini namoyish eta oladi',
    'about.vision.li2': 'Investorlar rivojlanayotgan bozorlardagi yangi imkoniyatlarni topadi',
    'about.vision.li3': 'Mentorlar tajribalarini keyingi avlod tadbirkorlari bilan bo‘lishadi',
    'about.vision.li4': 'Hamjamiyatlar global muammolarni hal qilish uchun chegaralar osha hamkorlik qiladi',
    'about.vision.p3': 'Biz shunchaki platforma emas, balki innovatorlarning salohiyatini ochib beradigan harakat quryapmiz.',
    'about.team.title': 'Jamoamiz bilan tanishing',
    'about.team.subtitle': 'Yosh innovatorlar va mentorlardan iborat ehtirosli jamoa.',
    'about.team.vasliddin': 'Vasliddin Isomiddinov',
    'about.team.vasliddinRole': 'Asoschi va direktor',
    'about.team.vasliddinDesc': 'Sarmoyavestning vizion, dizayn va rivojlanishini boshqaradi. Mahsulot yo‘nalishi va jamoa muvofiqlashtirilishini nazorat qiladi.',
    'about.team.asadbek': 'Asadbek Ismoilov',
    'about.team.asadbekRole': 'Loyiha maslahatchisi',
    'about.team.asadbekDesc': 'HKUSTda iqtisod talabasi. Sarmoyavestning strategik va moliyaviy yo‘nalishi bo‘yicha maslahatlar beradi.',
    'about.team.adiba': 'Adiba Isabekova',
    'about.team.adibaRole': 'Kommunikatsiyalar boshlig‘i',
    'about.team.adibaDesc': 'Brend kommunikatsiyasi, hikoya aytish va media ishtirokini boshqaradi.',
    'about.team.dauren': 'Dauren Ibragim',
    'about.team.daurenRole': 'Operatsiyalar va hamkorliklar boshlig‘i',
    'about.team.daurenDesc': 'Chegaradan tashqari hamkorliklarni muvofiqlashtiradi va loyiha operatsiyalarini boshqaradi.',

    // Footer
    'footer.tagline': 'Innovatorlarni investorlar bilan bog‘lab, kelajak avlod global startaplariga kuch beramiz.',
    'footer.platform': 'Platforma',
    'footer.aboutUs': 'Biz haqimizda',
    'footer.services': 'Xizmatlar',
    'footer.browseProjects': 'Loyihalarni ko‘rish',
    'footer.resources': 'Resurslar',
    'footer.resourcesLink': 'Resurslar',
    'footer.contact': 'Aloqa',
    'footer.connect': 'Bog‘lanish',
    'footer.copyright': '© {year} Sarmoyavest. Barcha huquqlar himoyalangan.',

    // Contact Page
    'contact.title': 'Biz bilan bog‘laning',
    'contact.subtitle': 'Savollaringiz bormi? Bizga xabar yuboring va biz imkon qadar tezroq javob beramiz.',
    'contact.formTitle': 'Bizga xabar yuboring',
    'contact.name': 'Ism',
    'contact.emailLabel': 'Email',
    'contact.subject': 'Mavzu',
    'contact.message': 'Xabar',
    'contact.namePlaceholder': 'To‘liq ismingiz',
    'contact.emailPlaceholder': 'sizning@email.com',
    'contact.subjectPlaceholder': 'Bu nima haqida?',
    'contact.messagePlaceholder': 'Batafsilroq yozing...',
    'contact.send': 'Xabar yuborish',
    'contact.infoTitle': 'Aloqa ma’lumotlari',
    'contact.email': 'Email',
    'contact.location': 'Manzil',
    'contact.locationText': 'Jizzax, O‘zbekiston',
    'contact.followUs': 'Bizni kuzating',
    'contact.officeHours': 'Aloqa soatlari',
    'contact.hoursText': 'Biz onlayn aloqadamiz va odatda 24 soat ichida javob beramiz.\nDushanba – Shanba: Faol\nYakshanba: Cheklangan javob',
    'contact.faqTitle': 'Ko‘p so‘raladigan savollar',
    'contact.faq1Q': 'Startapimni qanday yuboraman?',
    'contact.faq1A': 'Hisob yarating, profilingizni to‘ldiring va loyiha tafsilotlarini yuboring. Loyihangiz ko‘rib chiqilib, platformada e’lon qilinadi.',
    'contact.faq2Q': 'Sarmoyavestdan foydalanish bepulmi?',
    'contact.faq2A': 'Ha! Platformamiz innovatorlar va investorlar uchun butunlay bepul.',
    'contact.faq3Q': 'Qanday startaplar qo‘shilishi mumkin?',
    'contact.faq3A': 'Biz, ayniqsa Markaziy Osiyodagi, boshlang‘ich bosqich (pre-seed va seed) startaplariga e’tibor qaratamiz. Barcha sohalar marhamat.',
    'contact.missingInfo': 'Ma’lumot yetishmayapti',
    'contact.fillFields': 'Iltimos, barcha majburiy maydonlarni to‘ldiring.',
    'contact.messageSent': 'Xabar yuborildi!',
    'contact.willRespond': 'Imkon qadar tezroq javob beramiz.',

    // Projects Page
    'projects.heroTitle': 'Startaplarni kashf eting',
    'projects.heroSubtitle': 'Rivojlanayotgan bozorlardagi iste’dodli asoschilarning innovatsion loyihalarini ko‘ring',
    'projects.searchPlaceholder': 'Loyiha nomi, davlat yoki kalit so‘z bo‘yicha qidiring...',
    'projects.showing': '{count} ta loyiha ko‘rsatilmoqda',
    'projects.founder': 'Asoschi:',
    'projects.contactFounder': 'Asoschi bilan bog‘lanish',
    'projects.comingSoonTitle': 'Yana loyihalar tez orada',
    'projects.comingSoonText': 'Bu faqat dastlabki ko‘rinish. Ro‘yxatdan o‘tib loyihangizni yuborganingizdan so‘ng u shu yerda paydo bo‘ladi.',
    'projects.submitStartup': 'Startapingizni yuborish',

    // Resources Page
    'resources.title': 'Resurslar',
    'resources.subtitle': 'O‘rganing. Quring. O‘sing — innovatorlarga ta’sir o‘tkazish uchun kuch.',
    'resources.buildTitle': 'G‘oyangizni quring',
    'resources.buildSubtitle': 'Startap yuborishga tayyorgarlik va tuzilma uchun aniq, do‘stona qo‘llanmalar.',
    'resources.guide1Title': 'Aniq muammo bayonotini qanday yozish kerak',
    'resources.guide1Desc': 'Startapingiz hal qiladigan muammoni investorlar va foydalanuvchilarga aks-sado beradigan tarzda ifodalashni o‘rganing.',
    'resources.guide2Title': 'Yechimingizni qanday samarali tasvirlash',
    'resources.guide2Desc': 'Yechimingizni aniq taqdim etish va uning noyob qiymatini ta’kidlash san’atini o‘zlashtiring.',
    'resources.guide3Title': 'G‘oyangizni ajratib turuvchi maslahatlar',
    'resources.guide3Desc': 'Raqobatli muhitda startapingizni farqlash va e’tibor qozonish strategiyalarini kashf eting.',
    'resources.guide4Title': 'Maqsadli auditoriyangizni tushunish',
    'resources.guide4Desc': 'Mijozlaringizning ehtiyojlarini chinakam qondiradigan mahsulot yaratish uchun ularni aniqlang va tahlil qiling.',
    'resources.mentorshipTitle': 'Mentorlik dasturi',
    'resources.mentorshipDesc': 'Innovatorlarga g‘oyalarini sayqallashda yordam berish uchun mentorlik tarmog‘ini quryapmiz. Top universitetlar mentorlari bilan bog‘laning.',
    'resources.comingSoon': 'Tez orada',
    'resources.oneOnOne': 'Yakka tartibdagi sessiyalar',
    'resources.expertFeedback': 'Ekspert fikr-mulohazasi',
    'resources.growthStrategies': 'O‘sish strategiyalari',

    // Events
    'events.badge': 'Tadbirlar va bosqichlar',
    'events.heroTitle': 'Tadbirlar',
    'events.heroSubtitle': 'Kelgusi sessiyalarimizga qo‘shiling va bizning yo‘limizdagi muhim bosqichlar bilan tanishing.',
    'events.upcoming.heading': 'Kelgusi tadbir',
    'events.upcoming.badge': 'Tez orada',
    'events.upcoming.title': 'Ishonch iqtisodiyoti',
    'events.upcoming.date': '15-may',
    'events.upcoming.desc': 'Birmingem universiteti va Nazarboyev universitetidan spikerlar ishtirokida — muhokama iste’dod qanday baholanishi va nega bozorlar har doim ham eng yaxshilarni mukofotlamasligi haqida real misollar beradi.',
    'events.upcoming.cta': 'Kuzatib boring',
    'events.upcoming.soon': 'Tez orada',
    'events.past.heading': 'Bosib o‘tilgan yo‘l',
    'events.past.eventCount': 'tadbir o‘tkazildi',
    'events.past.completedBadge': 'Yakunlandi',
    'events.past.firstEvent.date': '16-yanvar',
    'events.past.speakerSubtitle': 'Tajriba ulashish va ilhomlantirish uchun taklif qilindi',
    'events.firstEvent.title': 'Ochilish sessiyasi: Investitsiya va moliyaviy fikrlash asoslari',
    'events.firstEvent.subtitle': 'Birinchi taklif etilgan spiker bilan tashabbusimiz boshlandi',
    'events.whatHappened.title': 'Tadbir sharhi',
    'events.whatHappened.desc': 'Ochilish sessiyasi tashabbusimizning rasmiy boshlanishini belgiladi va investitsiyalarga qiziquvchi talabalarni birlashtirdi. Sessiya interaktiv tarzda o‘tdi.',
    'events.guestSpeaker.title': 'Taklif etilgan spiker',
    'events.guestSpeaker.name': 'Asadbek Ismoilov',
    'events.guestSpeaker.role': 'Loyiha maslahatchisi',
    'events.guestSpeaker.bio': 'Asadbek Ismoilov, Levsha nomi bilan ham tanilgan, loyiha maslahatchisi va taklif etilgan spiker sifatida tadbirga qo‘shildi. HKUSTda iqtisod talabasi sifatida u moliyaviy savodxonlik va investitsiya tafakkuri bo‘yicha qimmatli fikrlarni baham ko‘rdi.',
    'events.gallery.title': 'Tadbir galereyasi',
    'events.gallery.photo1': 'Asosiy tadbir fotosini yuklash',
    'events.gallery.photo2': 'Tadbir fotosi 2 ni yuklash',
    'events.gallery.photo3': 'Tadbir fotosi 3 ni yuklash',
    'events.gallery.featured': 'Asosiy',
    'events.whyItMattered.title': 'Nega bu muhim edi',
    'events.whyItMattered.desc': '[Ushbu birinchi tadbir tashkilot va hamjamiyat uchun nega muhim bo‘lganini tushuntiring.]',
    'events.keyInsights.title': 'Asosiy xulosalar',
    'events.keyInsights.p1': 'Bu hatto kichik, sodiq guruh ham mazmunli muhokamalar yaratishi mumkinligini ko‘rsatdi.',
    'events.keyInsights.p2': 'Ushbu ochilish sessiyasining muvaffaqiyati kelajakdagi katta tadbirlar uchun zamin yaratdi.',
    'events.nav.previous': 'Oldingi tadbir',
    'events.nav.next': 'Keyingi tadbir',
    'events.nav.counter': '{current}-tadbir / {total}',
    'events.secondEvent.date': '10-mart',
    'events.secondEvent.title': 'G‘oyadan ta’sirgacha: Toshkentdagi shahar trafigini hal qilish',
    'events.secondEvent.subtitle': 'Interaktiv "Qog‘ozdan amaliyotgacha" sessiyasi',
    'events.secondEvent.overviewTitle': 'Tadbir sharhi',
    'events.secondEvent.overviewDesc': 'Bu sessiya interaktiv "Qog‘ozdan amaliyotgacha" tajribasi sifatida tashkil etildi. Toshkentdagi tirbandlikni misol qilib, ishtirokchilar amaliy yechimlarni nazariy, amalga oshirilishi va investitsion salohiyat nuqtai nazaridan baholashdi.',
    'events.secondEvent.galleryTitle': 'Tadbir galereyasi',
    'events.secondEvent.featured': 'Asosiy',
    'events.secondEvent.whatHappenedTitle': 'Nima sodir bo‘ldi',
    'events.secondEvent.whatHappenedDesc': 'Ishtirokchilar guruhlarga bo‘linib, har bir guruhga bitta yechimni tahlil qilish va himoya qilish topshirildi. Tuzilgan muhokamalardan keyin har bir guruh argumentlarini taqdim etdi va sessiya ochiq munozara bilan yakunlandi.',
    'events.secondEvent.impactTitle': 'Ta’sir',
    'events.secondEvent.impactDesc': 'Bu sessiya Sarmoyavest ichida yanada interaktiv va amaliy o‘rganishga qadam bo‘ldi. Iqtisodiy nazariyani real muammolarni hal qilish bilan birlashtirib, ishtirokchilar tanqidiy fikrlashga muvaffaq bo‘lishdi.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};